---
- name: Converge
  hosts: all
  roles:
    - role: ansible-role-keyboard
      keyboard_model: pc105
      keyboard_layout: brai
      keyboard_variant: right_hand
      keyboard_options: 'lv3:alt_switch,compose:rctrl'
      keyboard_backspace: guess
